FROM node:10.15.0-alpine

ARG HTTP_PROXY
ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTP_PROXY
ENV NO_PROXY "*.tellme.com,*.247-inc.net,127.0.0.1"

# git + ssh so that npm can install git-based deps
# zip to package the artifact to send to nexus
RUN apk update && \
  apk add git openssh-client zip python2=2.7.15-r1 make g++ curl && \
  rm /var/cache/apk/* && \
  adduser -D -u 32006 jenkins
